[gcp_service_account]
type = "service_account"
project_id = "skillful-mason-454117-m5"
private_key_id = "198b99e1deb517d62cb16a682df1da2a2a61f657"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDANrX7PtxDHXH0
rDhP9nhiUiuwS+jFlVViiutSIxXp9dqkSn8x4OdnDjD0cqon6d7gmUFUIonkpoK9
OlYwxT0JqsRZMToblGTSou9THbVsjpsf/I6r0fXLxN6lqRXhNdBL1M3IVPSsQzq4
cm5gJxUMgqUlnp5/5qTiXwbTm6mFxGask3MVBDzU+ojK9R5j8COMsOXJPSoez1iy
Se/V14ZoiWqyz0Ro2Yi1yJSrZE4T0KxPWr7WfgiW5F/8tPdxQLkWPRkXF9MM33Gt
/XQEkcpUn+DtI+mKrKUcLzKj/GXem3SFbUhAGbXM8Qa6TzqG5sYtqtTxLPyP5v4M
xGBE0ffpAgMBAAECggEAEl44EkAdztkVvnals/h+5RBqpeB/KEB+xhm15qW9Lpwk
rm4DDSprmpTH11hMy98kwgxLKqXZTQ0fccNNIMB8dnvH4ykZ3zBVWS6iVaxBXdQb
3VjmbmN0TGpuB2Eq2thoZRK7LoF11y9egWlIBG6/q3AhpYBsr5bEG3DOx3J45vQl
IJ/OzOa7fsklDxzyssm9HmrZY8UV6Gk32PNLaoRMLgnt1BVGhjXS5o7D93soT5nX
DyFOj+IHdLZlBMNAgdp47aV7CdAgzYSdZ+J2/ShUe6jetrVUTTlbo9O3Z6qLLb6k
l28puYjEMhwf5MOTH55qacFrHxfYw847d8GsSVLBHQKBgQDgK9EMc9WSUG8MtBZw
UnXX7PHWjPqvuYVvwZQYwKC7+DzY87Jt1vjlhmF6nSAjUOdIWUvgt0d6JQ2YWraR
F2yfLRivZOh9ynQMHtlbHRAawgC8lIQ6JhGMIxM5J+YUZe63k14cqqdGWmAs5Sht
C05ErvHlrZMigQLnKgLCZm73NQKBgQDbgU27XlZkZKfHFl5qtuMy5cJRLLpCfz1+
SUtaEcgpEIKyBKO3ZEvKe48uKC1OGU72Wgw5KBb+/RIiKGfKA5RnaGzuPzPQhFOB
6DdoC/H9E0GSA9LPpxXLVKNMHIJxd0rQivAGp2cFeEFI0TKzzetsONHvih1L3NZy
JKyf8X6wZQKBgBCz0xCddNVA/vUwWdemnTcoZWB6ApejOAj6oGEzwQYgWdBEYBAF
C2h2mb68BE/9UC440Ql+PmogZqHqaF3pI+O8RXGUECqHMhxRFBrQ0Ild2RYz7qIy
ge4yEtWYXnE4ow+0gDeck3gPdckCjf+J7xv4+PcG9saEXEYDAE+huDTdAoGAKR3L
ZbGCFUQVeWFjRjID1ODcyT/Lk/Epn6IzDygNikOhd58O26dZ2w/R/h9gfSSYeeTc
LUipJhJZdzSCXIDXJ5eT7/y+w+xFiCvrVP4H0hPtUGCO+H6fwnqULAmbFY324aFk
3Jo23ftsnyswiCWmV5s9F9WTL0aqlK7x9vPRe1ECgYEAuZZszFrhPoBzY24UUkTV
pmYQ/rsN0zHu3i5zxr6bZ8yzKBfcHrIZjgcjKA29TZu/09F/LoAH5yk4S65jhlfN
b7IOq+FEfcEfanzdcq4W/To48eI3VqqpD9ug/nfPz272JUe5cpitgZI9xImhMeKW
8sHFWUVU2RReqp9oIMSTNfA=
-----END PRIVATE KEY-----
"""
client_email = "admin101@skillful-mason-454117-m5.iam.gserviceaccount.com"
client_id = "106146706931150010069"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/admin101%40skillful-mason-454117-m5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
